///////////////////////////////////////////////////////////
//  Poloha.cs
//  Implementation of the Class Poloha
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:22
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

using System;

namespace SimulacnaHra.hra {

    /// <summary>
    /// Trieda Poloha zjednoduËuje pr·cu so s˙radnicami
    /// </summary>
	public class Poloha {

		private int aRiadok;
		private int aStpec;

        /// <summary>
        /// Riadok - teda Y os
        /// </summary>
        public int Riadok { get { return aRiadok; } set { aRiadok = value; } }

        /// <summary>
        /// StÂpec - tada X os
        /// </summary>
        public int Stlpec { get { return aStpec; } set { aStpec = value; } }

        /// <summary>
        /// Vytv·ra nov˙ polohu
        /// </summary>
        /// <param name="paRiadok">riadok</param>
        /// <param name="paStplec">stÂpec</param>
		public Poloha(int paRiadok, int paStplec){
            aRiadok = paRiadok;
            aStpec = paStplec;
		}


		/// <summary>
		/// Najkratöia vzdialenosù medzi dvomi polohami
		/// </summary>
		/// <param name="paPoloha"></param>
		/// <returns>celÈ ËÌslo -> vzdialenosù</returns>
		public int Vzdialenost(Poloha paPoloha){
            return Math.Abs(aRiadok - paPoloha.Riadok) + Math.Abs(aStpec - paPoloha.Stlpec);
		}

	}//end Poloha

}//end namespace Hra