///////////////////////////////////////////////////////////
//  Sprava.cs
//  Implementation of the Class Sprava
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:22
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

using System;
using System.Windows.Forms;


namespace gui {

    /// <summary>
    /// Statick· trieda, ktor· zobrazuje spr·vy hr·Ëovi
    /// </summary>
	public class Sprava {

		/// <summary>
		/// Zobrazenie jednoduchej spr·vy
		/// </summary>
		/// <param name="paText">Text spr·vy</param>
		public static void Info(String paText){
            MessageBox.Show(paText, "Info", MessageBoxButtons.OKCancel, MessageBoxIcon.Asterisk);
		}

	}//end Sprava

}//end namespace gui