///////////////////////////////////////////////////////////
//  Sprava.cs
//  Implementation of the Class Sprava
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:22
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

using System;
using System.Windows.Forms;

namespace SimulacnaHra.gui {

    /// <summary>
    /// Statická trieda, ktorá zobrazuje správy hráèovi
    /// </summary>
	public class Sprava {

		/// <summary>
		/// Zobrazenie jednoduchej správy
		/// </summary>
		/// <param name="paText">Text správy</param>
		public static void Info(String paText){
            MessageBox.Show(paText, "Info", MessageBoxButtons.OKCancel, MessageBoxIcon.Asterisk);
		}

        public static bool DajNaVyber(String paText)
        {
            DialogResult dialogResult = MessageBox.Show(paText, "Výber z možností", MessageBoxButtons.YesNo);
            if (dialogResult == DialogResult.Yes)
            {
                return true;
            }
            return false;
        }

	}//end Sprava

}//end namespace gui