///////////////////////////////////////////////////////////
//  Mesto.cs
//  Implementation of the Class Mesto
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:22
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

using System;
using SimulacnaHra.gui;
using SimulacnaHra.hra;
using SimulacnaHra.matematika;

namespace SimulacnaHra.prvkyHry.vyroba {

    /// <summary>
    /// Trieda reprezentuj˙ca mesto
    /// </summary>
	public class Mesto : Vyroba {

		private int aPriprastok;
	    private const int cIntervalDni = 30;
        private int aDen;
        private int aPoradoveCislo;

        /// <summary>
        /// N·zov mesta
        /// </summary>
        public string Nazov { get; internal set; }

        /// <summary>
        /// Popul·cia mesta
        /// </summary>
        public int Populacia { get; internal set; }

	    /// <summary>
	    /// Inicializ·cia mesta, v˝ber n·zvu a n·hodne zvolenie poËiatoËnej popul·cia podæa trojuholnÌkovÈho rozdelenia
	    /// </summary>
	    /// <param name="paPoloha">poloha</param>
	    /// <param name="paPoradoveCislo">poradsovÈ ËÌslo</param>
	    public Mesto(Poloha paPoloha, int paPoradoveCislo): base(DruhVyroby.Mesto, paPoloha)
        {
            aDen = 0;
            aPoradoveCislo = paPoradoveCislo;
            int poradie = 0;

            foreach( NazvyMiest nazov in Enum.GetValues(typeof(NazvyMiest)))
            {
                if(aPoradoveCislo == poradie)
                {
                    Nazov = nazov.ToString();
                    break;
                }
                poradie++;
            }

            Populacia = Nahoda.TriaInt(100, 300, 400);
            this.ZmenPrirastok();
		}

        /// <summary>
        /// RozËÌrenie mesta
        /// </summary>
        private void RozsirSa()
        {
            Populacia += aPriprastok;
		}

        /// <summary>
        /// Zmena prÌrastku
        /// </summary>
        private void ZmenPrirastok()
        {
            aPriprastok = Populacia / Nahoda.NahodnyInt(45, 55);
		}

        /// <summary>
        /// Mesto potrebuje vedieù, ûe preöiel deÚ, kaûd˝ zadan˝ poËet dnÌ sa rozöÌri
        /// </summary>
        public void PrechodDna() {
            aDen++;
            if (cIntervalDni == aDen)
            {
                aDen = 0;
                this.RozsirSa();
                this.ZmenPrirastok();
                Console.WriteLine(this.ToString());
                
            }
            this.Vyrob();
        }

        /// <summary>
        /// Vyrobenie - teda vznikn˙ cestuj˙ci a poöta
        /// </summary>
        public void Vyrob() 
        {
            if(Zoskupenie != null)
            {
                int temp = Populacia / cIntervalDni;

                int pocetCestujucich = temp/5;

                if (pocetCestujucich > 0)
                {
                    pocetCestujucich = Nahoda.TriaInt(pocetCestujucich - 1, pocetCestujucich, pocetCestujucich + 2);
                }
                else 
                {
                    pocetCestujucich = 1;
                }

                int pocetPosty = temp / 10;

                if (pocetPosty > 0)
                {
                    pocetPosty = Nahoda.TriaInt(pocetPosty - 1, pocetPosty, pocetPosty + 2);
                }
                else
                {
                    pocetPosty = 1;
                }

                for (int i = 0; i < pocetCestujucich; i++)
                {
                    Zoskupenie.NechajCakat(new PrepravJednotka(TypPrepravJednotky.cestujuci));
                }

                for (int i = 0; i < pocetPosty; i++)
                {
                    Zoskupenie.NechajCakat(new PrepravJednotka(TypPrepravJednotky.posta));
                }
                Console.WriteLine("Mesto, cest: " + pocetCestujucich + ", post: " + pocetPosty);
            }
        }

        public override string ToString() {
            return Nazov + " (" +Populacia+")"  ;
        }


	}//end Mesto

}//end namespace vyroba