///////////////////////////////////////////////////////////
//  TypPrepravJednotky.cs
//  Implementation of the Enumeration TypPrepravJednotky
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:23
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

namespace SimulacnaHra.prvkyHry.vyroba {

    /// <summary>
    /// Druhy prepravných jednotiek a ich základné jednotkové ceny za prepravu
    /// </summary>
	public enum TypPrepravJednotky : int {

		cestujuci = 20,
		posta = 25,
		uhlie = 40,
		zeleznaRuda = 38,
		drevo = 32,
		ropa = 31,
		dobytok = 24,
		obilie = 26,
		ocel = 37,
		tovar = 29

	}//end TypPrepravJednotky

}//end namespace vyroba