///////////////////////////////////////////////////////////
//  Tlacitko.cs
//  Implementation of the Class Tlacitko
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:22
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

using System.Drawing;

namespace SimulacnaHra.prvkyHry.ovladanie {

    /// <summary>
    /// Tirida, ktorá sa reprezentuje tlaèítka
    /// </summary>
	public class Tlacitko {

        private Rectangle aObsah;
        private VykonavanaCinnost aTyp;

        /// <summary>
        /// Inicializácia
        /// </summary>
        /// <param name="paX">poloha X</param>
        /// <param name="paY">poloha Y</param>
        /// <param name="paSirka"> šírka</param>
        /// <param name="paVyska">výška</param>
        /// <param name="paTyp">typ - teda na èo slúži</param>
		public Tlacitko(int paX, int paY, int paSirka, int paVyska, VykonavanaCinnost paTyp){
            aTyp = paTyp;
            aObsah = new Rectangle(paX, paY, paSirka, paVyska);
		}

        /// <summary>
        /// Spracovanie kliknutia
        /// </summary>
        /// <param name="paX"></param>
        /// <param name="paY"></param>
        /// <returns></returns>
        public bool Kliknute(int paX, int paY) { 
            Rectangle kurzor = new Rectangle(paX, paY, 1, 1);
            if (aObsah.Contains(kurzor))
            {

                return true;
            }
            return false;
        }

        /// <summary>
        /// Vrátenie typu
        /// </summary>
        /// <returns></returns>
        public VykonavanaCinnost DajTyp() {
            return aTyp;
        }

        public string ToString() {
            return "Tlacitko: " + aTyp.ToString(); 
        }
	}
}