///////////////////////////////////////////////////////////
//  Boja.cs
//  Implementation of the Class Boja
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:21
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

using System;
using SimulacnaHra.hra;
using SimulacnaHra.prvkyHry.dopravneProstriedky;
using SimulacnaHra.Properties;

namespace SimulacnaHra.prvkyHry.infrastruktura {

    /// <summary>
    /// Boja slúži na orientáciu lodí.
    /// </summary>
    [Serializable]
	public class Boja : MiestoZastavenia {

        /// <summary>
        /// Inicializácia potrebných vecí
        /// </summary>
        /// <param name="paPoloha"></param>
		public Boja(Poloha paPoloha){

            Poloha = paPoloha;
            NastavObrazok(Resources.boja, "boja");
            ZburatelneAutomaticky = false;
            NakladyNaZburanie = 50;
            Cena = 100;
            MozePriat = DruhVozidla.vodne;
		}

	    public override string ToString()
	    {
	        return "Bója";
	    }
	}//end Boja

}//end namespace infrastruktura