///////////////////////////////////////////////////////////
//  Dok.cs
//  Implementation of the Class Dok
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:21
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using SimulacnaHra.hra;
using SimulacnaHra.prvkyHry.dopravneProstriedky;
using SimulacnaHra.prvkyHry.vyroba;
using SimulacnaHra.Properties;

namespace SimulacnaHra.prvkyHry.infrastruktura {

    /// <summary>
    /// Dok je stanica pre lode
    /// </summary>
	public class Dok : Stanica {

        private List<PrototypDp> aMozneStroje;

        /// <summary>
        /// Stroje, ktorÈ je moûnÈ v danom doku postaviù
        /// </summary>
        public override List<PrototypDp> MozneStroje
        {
            get { return aMozneStroje; }
        }

        /// <summary>
        /// Konötruktor pre dok, ktor˝ mÙûe byù s˙Ëasùou ropnej ploöiny
        /// </summary>
        /// <param name="paPoloha"></param>
	    public Dok(Poloha paPoloha)
		{
		    Poloha = paPoloha;
            DokonciVytvaranie();
		}

        /// <summary>
        /// Konötruktor pe dok, ktor˝ stavia hr·Ë
        /// </summary>
        /// <param name="paPoloha"></param>
        /// <param name="paSmerDoku"></param>
        public Dok(Poloha paPoloha, SmerDoku paSmerDoku)
        {
            ZburatelneAutomaticky = false;
            NakladyNaZburanie = 300;
            Cena = 700;

            Poloha = paPoloha;

            switch (paSmerDoku) 
            {
                case SmerDoku.dole:
                    NastavObrazok(Resources.dokDole, "dokDole");
                    break;
                case SmerDoku.hore:
                    NastavObrazok(Resources.dokHore, "dokHore");
                    break;
                case SmerDoku.vlavo:
                    NastavObrazok(Resources.dokVlavo, "dokVlavo");
                    break;
                case SmerDoku.vpravo:
                    NastavObrazok(Resources.dokVpravo, "dokVpravo");
                    break;
            }
            DokonciVytvaranie();
        }

        /// <summary>
        /// DokonËenie vytv·rania
        /// </summary>
	    private void DokonciVytvaranie()
	    {
            aMozneStroje = new List<PrototypDp>();
            Predlohy();
	    }

        /// <summary>
        /// Vytvorenie predlÙh - teda strojov, ktorÈ je moûnÈ zak˙più
        /// </summary>
        private void Predlohy()
        {
            aMozneStroje.Add(new Lod(Poloha, TypPrepravJednotky.cestujuci, 30, 30, 75000, "V˝letn· loÔ"));
            aMozneStroje.Add(new Lod(Poloha, TypPrepravJednotky.cestujuci, 100, 40, 345000, "RieËny parnÌk"));
            aMozneStroje.Add(new Lod(Poloha, TypPrepravJednotky.cestujuci, 120, 110, 520200, "Vzn·öadlo Pegasus"));
            aMozneStroje.Add(new Lod(Poloha, TypPrepravJednotky.cestujuci, 1200, 39, 4301000, "MS European Voyager"));
            aMozneStroje.Add(new Lod(Poloha, TypPrepravJednotky.posta, 60, 35, 120000, "Mal· poötov· loÔ"));
            aMozneStroje.Add(new Lod(Poloha, TypPrepravJednotky.posta, 150, 35, 300000, "Veæk· poötov· loÔ"));
            aMozneStroje.Add(new Lod(Poloha, TypPrepravJednotky.ropa, 100, 70, 223000, "Mal˝ tanker"));
            aMozneStroje.Add(new Lod(Poloha, TypPrepravJednotky.ropa, 250, 55, 456500, "Stredn˝ tanker"));
            aMozneStroje.Add(new Lod(Poloha, TypPrepravJednotky.ropa, 1000, 42, 4500680, "Veæk˝ tanker"));
            MozePriat = DruhVozidla.vodne;
        }

	    public override String ToString()
        {
            return "Dok";
        }

	    public override bool PostavStroj(int paPor)
	    {
            if (paPor >= 0 && paPor < aMozneStroje.Count)
            {
                Lod lodStavana = new Lod(aMozneStroje[paPor]);
                if (Spolocnost.UpravFinancie(-lodStavana.Cena))
                {
                    DopravnyProstriedok dp = new DopravnyProstriedok(lodStavana);
                    Hra.DajInstanciu().Spolocnost.PridajDP(dp);
                    PridajOdstavene(dp);
                }
            }
            return false;
	    }
	}//end Dok

}//end namespace infrastruktura