///////////////////////////////////////////////////////////
//  Infrastruktura.cs
//  Implementation of the Class Infrastruktura
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:21
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

using SimulacnaHra.hra;
using SimulacnaHra.prvkyHry.dopravneProstriedky;
using SimulacnaHra.prvkyHry.mapa;

namespace SimulacnaHra.prvkyHry.infrastruktura {

    /// <summary>
    /// Spoloèný abstraktný predok všetkej infraštruktúry
    /// </summary>
	public abstract class Infrastruktura : ZakladObrazku
	{

	    private Poloha aPoloha;

        private bool aZburatelne;
        public bool ZburatelneAutomaticky { get { return aZburatelne; } set { aZburatelne = value; } }
        public int Cena { get; set; }
        public int NakladyNaZburanie { get; set; }

        /// <summary>
        /// Poloha - pri nastavení prepoèítava polohu aj pre potreby vykreslovania
        /// </summary>
        public Poloha Poloha {
            get { return aPoloha; }
            set
            {
                aPoloha = value;
                OdsadenieZHora = aPoloha.Riadok * Policko.cVelkostPolicka;
                OdsadenieZLava = aPoloha.Stlpec * Policko.cVelkostPolicka;
            }
        }
        public DruhVozidla Povolene { get; set; }

        public void PridajPovolenyProstriedok() {
        }
    }//end Infrastruktura

}//end namespace infrastruktura