///////////////////////////////////////////////////////////
//  MiestoZastavenia.cs
//  Implementation of the Class MiestoZastavenia
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:22
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

using System;
using SimulacnaHra.prvkyHry.dopravneProstriedky;

namespace SimulacnaHra.prvkyHry.infrastruktura {

    /// <summary>
    /// Predok miest zastavenia. Za tie je povaovaná kadı stanica a bója
    /// </summary>
    [Serializable]
	public abstract class MiestoZastavenia : Infrastruktura {

        private int aPocetObsluhovanychStrojov;
	    public abstract override string ToString();

        /// <summary>
        /// Ktorı z druhov vozidiel príjma
        /// </summary>
	    public DruhVozidla MozePriat { get; set; }

        /// <summary>
        /// Ak tam nie sú obsluhované stroje, tak je moné toto miesto zbúra
        /// </summary>
	    public bool MozemZburat {
	        get {
                if (aPocetObsluhovanychStrojov >0)
                {
                    return false;
                }
	            return true;
	        }
	    }

	    protected MiestoZastavenia()
	    {
	        aPocetObsluhovanychStrojov = 0;
	    }

        /// <summary>
        /// uprava poètu obsluhovanıch strojov
        /// </summary>
	    public void ZvysPobluhovane()
	    {
	        aPocetObsluhovanychStrojov++;
	    }

        /// <summary>
        /// uprava poètu obsluhovanıch strojov
        /// </summary>
	    public void ZnizObsluhovane()
	    {
	        aPocetObsluhovanychStrojov--;
	    }

	}//end MiestoZastavenia

}//end namespace infrastruktura