///////////////////////////////////////////////////////////
//  Priproda.cs
//  Implementation of the Class Priproda
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:22
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

using System;
using SimulacnaHra.hra;
using SimulacnaHra.matematika;
using SimulacnaHra.Properties;


namespace SimulacnaHra.prvkyHry.infrastruktura {

	/// <summary>
	/// Prírodnı objekt, nemá hlbší vıznam, len to, e ho 
	/// je nutné zbúra keï chce hráè stava a zároveò oivuje mapu
	/// 25% šanca na to, e to buse kameò a 75% e strom
	/// </summary>
    [Serializable]
	public class Priroda : Infrastruktura {

        private bool aJeStrom;
        public const int cNakladyStrom = 50;
        public const int cNakladySkala = 80;

		public Priroda(Poloha paPoloha)
		{

		    Poloha = paPoloha;

            aJeStrom = true;
            if (Nahoda.NahodneCislo0az1() < 0.25)
            {
                aJeStrom = false;
            }

            if (aJeStrom == true)
            {
                NastavObrazok(Resources.tree, "tree");
                NakladyNaZburanie = cNakladyStrom;
            }
            else {
                NastavObrazok(Resources.stone, "stone");
                NakladyNaZburanie = cNakladySkala;
            }

            base.ZburatelneAutomaticky = true;
		}

	}//end Priproda

}//end namespace infrastruktura