///////////////////////////////////////////////////////////
//  SmerZast.cs
//  Implementation of the Enumeration SmerZast
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:22
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

namespace SimulacnaHra.prvkyHry.infrastruktura {

    /// <summary>
    /// Smer zastávky a žel. stanice
    /// </summary>
	public enum SmerZast : int {

		horizontalny = 13,
		vertikalny = 14

	}//end SmerZast

}//end namespace infrastruktura