///////////////////////////////////////////////////////////
//  SmerInf.cs
//  Implementation of the Enumeration SmerInf
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:22
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

namespace SimulacnaHra.prvkyHry.infrastruktura {

    /// <summary>
    /// Smer Infraštruktúry
    /// </summary>
	public enum SmerInf : int {

		horizontalny = 1,
		vertikalny = 2,
		zatackaDoleVlavo = 3,
		zatackaDoleVpravo = 6,
		zatackaHoreVpravo = 5,
		zatackaHoreVlavo = 4

	}//end SmerInf

}//end namespace infrastruktura