///////////////////////////////////////////////////////////
//  SmerDoku.cs
//  Implementation of the Enumeration SmerDoku
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:22
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

namespace SimulacnaHra.prvkyHry.infrastruktura {

    /// <summary>
    /// Smer Doku
    /// </summary>
	public enum SmerDoku : int {

		hore = 3,
		dole = 1,
		vlavo = 2,
		vpravo = 4,
        boja = 5

	}//end SmerDoku

}//end namespace infrastruktura