///////////////////////////////////////////////////////////
//  Zastavka.cs
//  Implementation of the Class Zastavka
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:23
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using SimulacnaHra.hra;
using SimulacnaHra.prvkyHry.dopravneProstriedky;
using SimulacnaHra.prvkyHry.vyroba;
using SimulacnaHra.Properties;

namespace SimulacnaHra.prvkyHry.infrastruktura {

    /// <summary>
    /// Zastávke pre castné vozidlá
    /// </summary>
    [Serializable]
	public class Zastavka : Stanica {

	    private List<PrototypDp> aMozneStroje;

	    public SmerZast SmerZast { get; set; }
        public override List<PrototypDp> MozneStroje{get { return  aMozneStroje; }}

        public Zastavka(Poloha paPoloha, SmerZast paSmerZast)
        {
            Poloha = paPoloha;
            SmerZast = paSmerZast;
            aMozneStroje = new List<PrototypDp>();

            if (SmerZast == SmerZast.horizontalny)
            {
                NastavObrazok(Resources.cestaZastavkaVodor, "cestaZastavkaVodor");
            }
            else 
            {
                NastavObrazok(Resources.cestaZastavkaZvy, "cestaZastavkaZvy");
            }

            ZburatelneAutomaticky = false;
            NakladyNaZburanie = 200;
            Cena = 500;
            Predlohy();

		}


        private void Predlohy()
        {
            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.cestujuci, 35, 88, 10520, "Hereford Leopard Bus"));
            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.cestujuci, 37, 112, 13540, "Foster Bus"));
            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.cestujuci, 40, 127, 17200, "Foster MkII Superbus"));

            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.posta, 28, 88, 11520, "Reynard Mail Truck"));
            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.posta, 32, 112, 15500, "Perry Mail Truck"));

            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.tovar, 20, 88, 11520, "Craighead Goods Truck"));
            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.tovar, 23, 112, 15500, "Goss Goods Truck"));

            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.obilie, 25, 88, 11520, "Thomas Grain Truck"));
            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.obilie, 30, 112, 15500, "Goss Grain Truck"));

            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.dobytok, 20, 88, 11520, "Uhl Livestock Van"));
            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.dobytok, 22, 112, 15500, "Foster Livestock Van"));

            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.drevo, 22, 88, 11520, "Foster Wood Truck"));
            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.drevo, 25, 112, 15500, "Moreland Wood Truck"));

            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.uhlie, 25, 88, 11520, "Uhl Coal Truck"));
            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.uhlie, 28, 112, 15500, "DW Coal Truck"));

            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.zeleznaRuda, 25, 88, 11520, "Uhl Iron Ore Truck"));
            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.zeleznaRuda, 27, 112, 15500, "Chippy Iron Ore Truck"));

            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.ocel, 18, 88, 11520, "Uhl Steel Truck"));
            aMozneStroje.Add(new Auto(Poloha, TypPrepravJednotky.ocel, 20, 112, 15500, "Kelling Steel Truck"));

            MozePriat = DruhVozidla.cestne;
        }

        public override String ToString()
        {
            return "Zástavka pre cestné vozidlá";
        }

	    public override bool PostavStroj(int paPor)
	    {
            Spolocnost spol = Hra.DajInstanciu().Spolocnost;
            if (paPor >= 0 && paPor < aMozneStroje.Count)
            {
                Auto autoStavane = new Auto(aMozneStroje[paPor], SmerZast);
                if (spol.UpravFinancie(-autoStavane.Cena))
                {
                    DopravnyProstriedok dp = new DopravnyProstriedok(autoStavane);
                    spol.PridajDP(dp);
                    PridajOdstavene(dp);
                }
            }
            return false;
	    }
	}//end Zastavka

}//end namespace infrastruktura