///////////////////////////////////////////////////////////
//  Zeleznica.cs
//  Implementation of the Class Zeleznica
//  Generated by Enterprise Architect
//  Created on:      17-2-2016 17:13:23
//  Original author: Dobroslav Grygar
///////////////////////////////////////////////////////////


using System;
using SimulacnaHra.hra;
using SimulacnaHra.prvkyHry.dopravneProstriedky;
using SimulacnaHra.Properties;

namespace SimulacnaHra.prvkyHry.infrastruktura {

    [Serializable]
	public class Zeleznica : Infrastruktura {

		private SmerInf aOrientacia;

        public SmerInf Orientacia { get { return aOrientacia; } }

		public Zeleznica(SmerInf paSmer, Poloha paPoloha){

            base.ZburatelneAutomaticky = false;
            Poloha = paPoloha;
            aOrientacia = paSmer;

            switch (aOrientacia)
            {
                case SmerInf.horizontalny:
                    NastavObrazok(Resources.zelVodorovne, "zelVodorovne");
                    Cena = 300;
                    break;
                case SmerInf.vertikalny:
                    NastavObrazok(Resources.zelZvisle, "zelZvisle");
                    Cena = 300;
                    break;
                case SmerInf.zatackaDoleVlavo:
                    NastavObrazok(Resources.zelOdbVlavoDole, "zelOdbVlavoDole");
                    Cena = 320;
                    break;
                case SmerInf.zatackaDoleVpravo:
                    NastavObrazok(Resources.zelOdbVpravoDole, "zelOdbVpravoDole");
                    Cena = 320;
                    break;
                case SmerInf.zatackaHoreVlavo:
                    NastavObrazok(Resources.zelOdbVlavoHore, "zelOdbVlavoHore");
                    Cena = 320;
                    break;
                case SmerInf.zatackaHoreVpravo:
                    NastavObrazok(Resources.zelOdbVpravoHore, "zelOdbVlavoHore");
                    Cena = 320;
                    break;
            }

            NakladyNaZburanie = 20;
            Povolene = DruhVozidla.kolajove;
            
		}

	}//end Zeleznica

}//end namespace infrastruktura